name: Gerando artefato

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparando o golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Download dos arquivos 
        uses: actions/checkout@v4
      - name: Build da aplicação
        run: go build -o soma .
      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: artefato_golang
          path: soma
  testes:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: artefato_golang
      - name: Listar arquivos
        run: ls
      - name: Teste do artefato
        run: |
          resultado_esperado="110"
          resultado=$(./soma 33 77)
          if [ ${resultado} != ${resultado_esperado} ]; then
            echo "::error::O resultado esperado era ${resultado_esperado} e o resultado foi ${resultado}"
            exit 1
          fi

          resultado_esperado="51"
          resultado=$(./soma 19 32)
          if [ ${resultado} != ${resultado_esperado} ]; then
            echo "::error::O resultado esperado era ${resultado_esperado} e o resultado foi ${resultado}"
            exit 1
          fi