name: Gerando artefato

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparando o golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
          cache: false
      - name: Download dos arquivos 
        uses: actions/checkout@v4
      - name: Cache de dependências
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
      - name: Update go.mod e go.sum
        run: |
          go mod edit -require=github.com/softchris/math@v0.1.0
          go mod tidy
      - name: Build da aplicação
        run: go build -o soma .
      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: artefato_golang
          path: |
            soma
            go.mod
            go.sum
  testes:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: artefato_golang
      - name: Teste do artefato
        run: |
          chmod 744 soma

          resultado_esperado="110"
          resultado=$(./soma 33 77)
          if [ ${resultado} != ${resultado_esperado} ]; then
            echo "::error::O resultado esperado era ${resultado_esperado} e o resultado foi ${resultado}"
            exit 1
          fi

          resultado_esperado="51"
          resultado=$(./soma 19 32)
          if [ ${resultado} != ${resultado_esperado} ]; then
            echo "::error::O resultado esperado era ${resultado_esperado} e o resultado foi ${resultado}"
            exit 1
          fi